# Generated by Django 3.2.8 on 2021-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
                ('emp_last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
